import { describe, it, expect } from "vitest";
import { solve_a, solve_b } from "../src/day07";

const input = `
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
`.trim();

describe("day07 examples", () => {
  it("First example", () => {
    expect(solve_a(input)).toBe(21);
  });
  it("Second example", () => {
    expect(solve_b(input)).toBe(40);
  });
});
